### ISSUE TITLE
When filtering results, display shows 1/7

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#19]
If I search for Topoflow (or another model), it will filter the results, but the search will show (1/7).
This is incorrect, because there are no 7 topoflows

**Comment by dhruvp-8** [comment]
Resolved.

**Comment by dgarijo** [comment]
Thanks @dhruvp-8.
Just FYI, if in the comment of your commit you add "Fix #issueNumber" you will automatically close the issue. It's also easier for tracking which change fixed which issue
