### ISSUE TITLE
Once a category is selected, it cannot be unselected

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#25]
How to reproduce this error:
In the main page, click on a category (e.g., hydrology). Then I cannot unselect it unless I refresh the page. 
And if I look for another model (e.g., DSSAT) it returns no results (which makes sense because DSSAT is an agriculture model).

**Comment by dhruvp-8** [comment]
I have inserted a blank item to unselect the category
