### ISSUE TITLE
Model view improvements

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#27]
There are a few things a little off here:

- "label" on top should be "URI"
- Version should be on top as well, close to the current title.
- The model configuration could show a label/description. It would be more informative.

**Comment by maurya-rohit** [comment]
Number 1 and 3 are done. Number 2 will be taken care in version search.

**Comment by dhruvp-8** [comment]
Number 2 handled. For All Version each card will have version number but while filtering version from each card will be removed and set at top close to the title.
