### ISSUE TITLE
Variable-configuration improvements

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#30]
- It should be called "variable presentation"
- The column with the number is not informative, I would remove it.
- Instead of showing the URI, show the label (rdfs:label) of the variable presentation.
- Show the short name, description and standard name of the variable presentation

**Comment by maurya-rohit** [comment]
Added all the necessary information regarding the variable presentation. Only renaming the file is remaining which would be done in different commit because of merger conflict.
