### ISSUE TITLE
Migrate to Polymer 3

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#31]
After March 2019 Chrome will deprecate html imports. We should start moving into Polymer 3, which is better compatible with Firefox.

**Comment by dgarijo** [comment]
Oh, and do the upgrade in another branch

**Comment by dhruvp-8** [comment]
We are now successfully upgraded to Polymer 3. There has been change on how to get the app working because of introduction of Node.js to Polymer 3. You can find it in ReadMe of polymer3 branch.
