### ISSUE TITLE
Important feedback from users

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#43]
These are small but important changes in terms of usability.
The model explorer looks good and it's understandable. However, when looking into dataset specs, it would be nice to replace "Label" with "Variable code", as it is the code used in the datasets. When browsing input/output files, it would be nice to say: Variables on dataset

The Variable search is confusing, unfortunately. Instead of showing "Variable Presentation", it would be better to state whether the variable is an input or an output variable. Also, Yolanda said that it would be appropriate to have a link to the dataset spec where this variable appears.

When selecting a standard name, it is unclear to me what are the variables being shown below. If those are ALL the variable presentations referring to the standard name, then the page should say so.

Keep up the good work!

**Comment by dhruvp-8** [comment]
Polymer 3 is faster. For safe side, let me update in both.

**Comment by dgarijo** [comment]
Excellent. Thanks

**Comment by dhruvp-8** [comment]
What does the link to dataset where variable appears mean?
Is this a link [https://w3id.org/mint/instance/DSSAT_SRAD](url) for SRAD?

**Comment by dhruvp-8** [comment]
Ok got it, it means DSSAT_weatherFile for SRAD as it is an input variable.

**Comment by dgarijo** [comment]
yes :)
