### ISSUE TITLE
Error with new model catalog: I/O is incorrectly shown

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#44]
The new model catalog has a change in the structure of the URIs: we no longer use hashes and instead only use slash. What it used to be URI: https://w3id.org/mint/instance#DSSAT now is URI: https://w3id.org/mint/instance/DSSAT. This breaks the explorer when showing I/O. Instead of using the URI for showing names of things, you should use the label of a resource. That way no matter what are the changes to their URIs you will be able to show it properly.
Please fix asap. URIs are not likely to change, but in this case it was a requirement

**Comment by maurya-rohit** [comment]
I fixed the view model page and removed the # dependent code but this structure has been assumed in other places. Dhruv let me know if you need help in other places too.( variable-presentation and variable-configuration page)

**Comment by dgarijo** [comment]
@maurya-rohit please fix it up if you can as well, so we have a version working. Then we can focus on proper improvements. Also, did you fix this for polymer 2 or 3?

**Comment by maurya-rohit** [comment]
Yes, I will look into the new files as well, I fixed in the master branch so that is polymer 2.

**Comment by maurya-rohit** [comment]
I only updated in the master branch.

**Comment by dhruvp-8** [comment]
Fixed it for both versions.
