### ISSUE TITLE
Incomplete list of models loaded by default

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#6]
When I load the app, only 2 models are loaded. Why is this?

**Comment by dhruvp-8** [comment]
This has been set to 2 models by default. If you want I can load all the models.

**Comment by dhruvp-8** [comment]
Ok. Thanks, I will fix it.

**Comment by dhruvp-8** [comment]
Default set to 10.
