### ISSUE TITLE
The link next to models goes to a 404 page

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogExplorer#8]
If there is no link, it will go to http://localhost:8081/undefined. Instead, it should not appear.

**Comment by dhruvp-8** [comment]
Currently, this is no URI associated with the ELQ. However, I have fixed it to go to a specific 404 View.

**Comment by dgarijo** [comment]
But you do not want to go to 404 page.
What you want is that if there is no URI associated to a model, it should not be possible to click on the link (link should not appear)

**Comment by dhruvp-8** [comment]
Ok, I shall remove the link icons for the Models which do not have link associated with them.

**Comment by dhruvp-8** [comment]
Completed
